# 以下代码全部由天马咲希型千趣编写，属于 UI 代码
# 禁止未通知本人的情况下修改本文件代码的任何部分或数值
# 一旦未经告知本人而进行修改，出现任何问题，不负责任何维护义务，因为那不是我造成的，不要给我徒增工作量，谢谢喵
# 目前的代码已经过充分的测试验证过可行性与稳定性，因为修改文件导致新增的潜在Bug，也请自己测试与负责

init python:
    cg_groups = {
        "mikuri_01": [
            "images/cg/ev/ev113a.webp",
            "images/cg/ev/ev113b.webp",
        ],
        "mikuri_02": [
            "images/cg/hv/hv108a.webp",
            "images/cg/hv/hv108b.webp",
            "images/cg/hv/hv108c.webp",
            "images/cg/hv/hv108d.webp",
            "images/cg/hv/hv108e.webp",
        ],
        "mikuri_03": [
            "images/cg/hv/hv109a.webp",
            "images/cg/hv/hv109b.webp",
            "images/cg/hv/hv109c.webp",
            "images/cg/hv/hv109d.webp",
            "images/cg/hv/hv109e.webp",
            "images/cg/hv/hv109f.webp",
        ],
        "mikuri_04": [
            "images/cg/hv/hv110a.webp",
            "images/cg/hv/hv110b.webp",
            "images/cg/hv/hv110c.webp",
            "images/cg/hv/hv110d.webp",
            "images/cg/hv/hv110e.webp",
            "images/cg/hv/hv110f.webp",
            "images/cg/hv/hv110g.webp",
        ],
        "chieri_01": [
            "images/cg/ev/ev213a.webp",
            "images/cg/ev/ev213b.webp",
            "images/cg/ev/ev213c.webp",
        ],
        "chieri_02": [
            "images/cg/hv/hv208a.webp",
            "images/cg/hv/hv208b.webp",
            "images/cg/hv/hv208c.webp",
            "images/cg/hv/hv208d.webp",
            "images/cg/hv/hv208e.webp",
            "images/cg/hv/hv208f.webp",
        ],
        "chieri_03": [
            "images/cg/hv/hv209a.webp",
            "images/cg/hv/hv209b.webp",
            "images/cg/hv/hv209c.webp",
            "images/cg/hv/hv209d.webp",
            "images/cg/hv/hv209e.webp",
            "images/cg/hv/hv209f.webp",
        ],
        "chieri_04": [
            "images/cg/hv/hv210a.webp",
            "images/cg/hv/hv210b.webp",
            "images/cg/hv/hv210c.webp",
            "images/cg/hv/hv210d.webp",
            "images/cg/hv/hv210e.webp",
            "images/cg/hv/hv210f.webp",
            "images/cg/hv/hv210g.webp",
        ],
        "ichika_01": [
            "images/cg/ev/ev313a.webp",
            "images/cg/ev/ev313b.webp",
            "images/cg/ev/ev313c.webp",
        ],
        "ichika_02": [
            "images/cg/hv/hv308a.webp",
            "images/cg/hv/hv308b.webp",
            "images/cg/hv/hv308c.webp",
            "images/cg/hv/hv308d.webp",
            "images/cg/hv/hv308e.webp",
            "images/cg/hv/hv308f.webp",
            "images/cg/hv/hv308g.webp",
            "images/cg/hv/hv308h.webp",
        ],
        "ichika_03": [
            "images/cg/hv/hv309a.webp",
            "images/cg/hv/hv309b.webp",
            "images/cg/hv/hv309c.webp",
            "images/cg/hv/hv309d.webp",
            "images/cg/hv/hv309e.webp",
            "images/cg/hv/hv309f.webp",
            "images/cg/hv/hv309g.webp",
            "images/cg/hv/hv309h.webp",
        ],
        "ichika_04": [
            "images/cg/hv/hv310a.webp",
            "images/cg/hv/hv310b.webp",
            "images/cg/hv/hv310c.webp",
            "images/cg/hv/hv310d.webp",
            "images/cg/hv/hv310e.webp",
            "images/cg/hv/hv310f.webp",
        ],
        "nana_01": [
            "images/cg/ev/ev413a.webp",
            "images/cg/ev/ev413b.webp",
            "images/cg/ev/ev413c.webp",
            "images/cg/ev/ev413d.webp",
            "images/cg/ev/ev413e.webp",
        ],
        "nana_02": [
            "images/cg/hv/hv408a.webp",
            "images/cg/hv/hv408b.webp",
            "images/cg/hv/hv408c.webp",
            "images/cg/hv/hv408d.webp",
            "images/cg/hv/hv408e.webp",
            "images/cg/hv/hv408f.webp",
        ],
        "nana_03": [
            "images/cg/hv/hv409a.webp",
            "images/cg/hv/hv409b.webp",
            "images/cg/hv/hv409c.webp",
            "images/cg/hv/hv409d.webp",
            "images/cg/hv/hv409e.webp",
            "images/cg/hv/hv409f.webp",
        ],
        "nana_04": [
            "images/cg/hv/hv410a.webp",
            "images/cg/hv/hv410b.webp",
            "images/cg/hv/hv410c.webp",
            "images/cg/hv/hv410d.webp",
            "images/cg/hv/hv410e.webp",
            "images/cg/hv/hv410f.webp",
        ],
        "kaguya_01": [
            "images/cg/ev/ev513a.webp",
            "images/cg/ev/ev513b.webp",
            "images/cg/ev/ev513c.webp",
        ],
        "kaguya_02": [
            "images/cg/hv/hv508a.webp",
            "images/cg/hv/hv508b.webp",
            "images/cg/hv/hv508c.webp",
            "images/cg/hv/hv508d.webp",
            "images/cg/hv/hv508e.webp",
            "images/cg/hv/hv508f.webp",
        ],
        "kaguya_03": [
            "images/cg/hv/hv509a.webp",
            "images/cg/hv/hv509b.webp",
            "images/cg/hv/hv509c.webp",
            "images/cg/hv/hv509d.webp",
            "images/cg/hv/hv509e.webp",
            "images/cg/hv/hv509f.webp",
        ],
        "kaguya_04": [
            "images/cg/hv/hv510a.webp",
            "images/cg/hv/hv510b.webp",
            "images/cg/hv/hv510c.webp",
            "images/cg/hv/hv510d.webp",
            "images/cg/hv/hv510e.webp",
            "images/cg/hv/hv510f.webp",
        ],
        "mitsuki_01": [
            "images/cg/ev/ev601a.webp",
            "images/cg/ev/ev601b.webp",
        ],
        "mitsuki_02": [
            "images/cg/ev/ev602a.webp",
            "images/cg/ev/ev602b.webp",
            "images/cg/ev/ev602c.webp",
        ],
        "mitsuki_03": [
            "images/cg/ev/ev603a.webp",
            "images/cg/ev/ev603b.webp",
            "images/cg/ev/ev603c.webp",
            "images/cg/ev/ev603d.webp",
        ],
        "mitsuki_04": [
            "images/cg/ev/ev604a.webp",
            "images/cg/ev/ev604b.webp",
            "images/cg/ev/ev604c.webp",
            "images/cg/ev/ev604d.webp",
        ],
        "mitsuki_05": [
            "images/cg/ev/ev605a.webp",
            "images/cg/ev/ev605b.webp",
        ],
        "mitsuki_06": [
            "images/cg/ev/ev606a.webp",
            "images/cg/ev/ev606b.webp",
            "images/cg/ev/ev606c.webp",
            "images/cg/ev/ev606d.webp",
            "images/cg/ev/ev606e.webp",
        ],
        "mitsuki_07": [
            "images/cg/ev/ev607a.webp",
            "images/cg/ev/ev607b.webp",
        ],
        "mitsuki_08": [
            "images/cg/ev/ev608a.webp",
            "images/cg/ev/ev608b.webp",
            "images/cg/ev/ev608c.webp",
        ],
        "mitsuki_09": [
            "images/cg/ev/ev609a.webp",
            "images/cg/ev/ev609b.webp",
            "images/cg/ev/ev609c.webp",
            "images/cg/ev/ev609d.webp",
        ],
        "mitsuki_10": [
            "images/cg/ev/ev610a.webp",
            "images/cg/ev/ev610b.webp",
            "images/cg/ev/ev610c.webp",
        ],
        "mitsuki_11": [
            "images/cg/ev/ev611a.webp",
            "images/cg/ev/ev611b.webp",
            "images/cg/ev/ev611c.webp",
        ],
        "mitsuki_12": [
            "images/cg/ev/ev612a.webp",
            "images/cg/ev/ev612b.webp",
            "images/cg/ev/ev612c.webp",
        ],
        "mitsuki_13": [
            "images/cg/hv/hv601a.webp",
            "images/cg/hv/hv601b.webp",
            "images/cg/hv/hv601c.webp",
            "images/cg/hv/hv601d.webp",
            "images/cg/hv/hv601e.webp",
            "images/cg/hv/hv601f.webp",
            "images/cg/hv/hv601g.webp",
        ],
        "mitsuki_14": [
            "images/cg/hv/hv602a.webp",
            "images/cg/hv/hv602b.webp",
            "images/cg/hv/hv602c.webp",
            "images/cg/hv/hv602d.webp",
            "images/cg/hv/hv602e.webp",
            "images/cg/hv/hv602f.webp",
        ],
        "mitsuki_15": [
            "images/cg/hv/hv603a.webp",
            "images/cg/hv/hv603b.webp",
            "images/cg/hv/hv603c.webp",
            "images/cg/hv/hv603d.webp",
            "images/cg/hv/hv603e.webp",
            "images/cg/hv/hv603f.webp",
            "images/cg/hv/hv603g.webp",
        ],
        "mitsuki_16": [
            "images/cg/hv/hv604a.webp",
            "images/cg/hv/hv604b.webp",
            "images/cg/hv/hv604c.webp",
            "images/cg/hv/hv604d.webp",
            "images/cg/hv/hv604e.webp",
            "images/cg/hv/hv604f.webp",
        ],
        "mitsuki_17": [
            "images/cg/hv/hv605a.webp",
            "images/cg/hv/hv605b.webp",
            "images/cg/hv/hv605c.webp",
            "images/cg/hv/hv605d.webp",
            "images/cg/hv/hv605e.webp",
            "images/cg/hv/hv605f.webp",
        ],
        "mitsuki_18": [
            "images/cg/hv/hv606a.webp",
            "images/cg/hv/hv606b.webp",
            "images/cg/hv/hv606c.webp",
            "images/cg/hv/hv606d.webp",
            "images/cg/hv/hv606e.webp",
            "images/cg/hv/hv606f.webp",
        ],
        "mitsuki_19": [
            "images/cg/hv/hv607a.webp",
            "images/cg/hv/hv607b.webp",
            "images/cg/hv/hv607c.webp",
            "images/cg/hv/hv607d.webp",
            "images/cg/hv/hv607e.webp",
            "images/cg/hv/hv607f.webp",
            "images/cg/hv/hv607g.webp",
        ],
        "kohana_01": [
            "images/cg/ev/ev701a.webp",
            "images/cg/ev/ev701b.webp",
            "images/cg/ev/ev701c.webp",
            "images/cg/ev/ev701d.webp",
            "images/cg/ev/ev701e.webp",
        ],
        "kohana_02": [
            "images/cg/ev/ev702a.webp",
            "images/cg/ev/ev702b.webp",
            "images/cg/ev/ev702c.webp",
            "images/cg/ev/ev702d.webp",
        ],
        "kohana_03": [
            "images/cg/ev/ev703a.webp",
            "images/cg/ev/ev703b.webp",
            "images/cg/ev/ev703c.webp",
            "images/cg/ev/ev703d.webp",
            "images/cg/ev/ev703e.webp",
            "images/cg/ev/ev703f.webp",
            "images/cg/ev/ev703g.webp",
            "images/cg/ev/ev703h.webp",
            "images/cg/ev/ev703i.webp",
            "images/cg/ev/ev703j.webp",
            "images/cg/ev/ev703k.webp",
            "images/cg/ev/ev703l.webp",
            "images/cg/ev/ev703m.webp",
            "images/cg/ev/ev703n.webp",
            "images/cg/ev/ev703o.webp",
        ],
        "kohana_04": [
            "images/cg/ev/ev704a.webp",
            "images/cg/ev/ev704b.webp",
            "images/cg/ev/ev704c.webp",
            "images/cg/ev/ev704d.webp",
        ],
        "kohana_05": [
            "images/cg/ev/ev705a.webp",
            "images/cg/ev/ev705b.webp",
            "images/cg/ev/ev705c.webp",
            "images/cg/ev/ev705d.webp",
        ],
        "kohana_06": [
            "images/cg/ev/ev706a.webp",
            "images/cg/ev/ev706b.webp",
            "images/cg/ev/ev706c.webp",
            "images/cg/ev/ev706d.webp",
        ],
        "kohana_07": [
            "images/cg/ev/ev707a.webp",
            "images/cg/ev/ev707b.webp",
            "images/cg/ev/ev707c.webp",
            "images/cg/ev/ev707d.webp",
        ],
        "kohana_08": [
            "images/cg/ev/ev708a.webp",
            "images/cg/ev/ev708b.webp",
            "images/cg/ev/ev708c.webp",
            "images/cg/ev/ev708d.webp",
        ],
        "kohana_09": [
            "images/cg/ev/ev709a.webp",
            "images/cg/ev/ev709b.webp",
        ],
        "kohana_10": [
            "images/cg/ev/ev710a.webp",
            "images/cg/ev/ev710b.webp",
        ],
        "kohana_11": [
            "images/cg/ev/ev711a.webp",
            "images/cg/ev/ev711b.webp",
            "images/cg/ev/ev711c.webp",
            "images/cg/ev/ev711d.webp",
            "images/cg/ev/ev711e.webp",
        ],
        "kohana_12": [
            "images/cg/ev/ev712a.webp",
            "images/cg/ev/ev712b.webp",
        ],
        "kohana_13": [
            "images/cg/hv/hv701a.webp",
            "images/cg/hv/hv701b.webp",
            "images/cg/hv/hv701c.webp",
            "images/cg/hv/hv701d.webp",
            "images/cg/hv/hv701e.webp",
        ],
        "kohana_14": [
            "images/cg/hv/hv702a.webp",
            "images/cg/hv/hv702b.webp",
            "images/cg/hv/hv702c.webp",
            "images/cg/hv/hv702d.webp",
            "images/cg/hv/hv702e.webp",
            "images/cg/hv/hv702f.webp",
            "images/cg/hv/hv702g.webp",
        ],
        "kohana_15": [
            "images/cg/hv/hv703a.webp",
            "images/cg/hv/hv703b.webp",
            "images/cg/hv/hv703c.webp",
            "images/cg/hv/hv703d.webp",
            "images/cg/hv/hv703e.webp",
        ],
        "kohana_16": [
            "images/cg/hv/hv704a.webp",
            "images/cg/hv/hv704b.webp",
            "images/cg/hv/hv704c.webp",
            "images/cg/hv/hv704d.webp",
            "images/cg/hv/hv704e.webp",
            "images/cg/hv/hv704f.webp",
            "images/cg/hv/hv704g.webp",
        ],
        "kohana_17": [
            "images/cg/hv/hv705a.webp",
            "images/cg/hv/hv705b.webp",
            "images/cg/hv/hv705c.webp",
            "images/cg/hv/hv705d.webp",
            "images/cg/hv/hv705e.webp",
        ],
        "kohana_18": [
            "images/cg/hv/hv706a.webp",
            "images/cg/hv/hv706b.webp",
            "images/cg/hv/hv706c.webp",
            "images/cg/hv/hv706d.webp",
            "images/cg/hv/hv706e.webp",
            "images/cg/hv/hv706f.webp",
            "images/cg/hv/hv706g.webp",
            "images/cg/hv/hv706h.webp",
        ],
        "kohana_19": [
            "images/cg/hv/hv707a.webp",
            "images/cg/hv/hv707b.webp",
            "images/cg/hv/hv707c.webp",
            "images/cg/hv/hv707d.webp",
            "images/cg/hv/hv707e.webp",
            "images/cg/hv/hv707f.webp",
            "images/cg/hv/hv707g.webp",
        ],
        "haremu_01": [
            "images/cg/hv/hv005a.webp",
            "images/cg/hv/hv005b.webp",
            "images/cg/hv/hv005c.webp",
            "images/cg/hv/hv005d.webp",
            "images/cg/hv/hv005e.webp",
            "images/cg/hv/hv005f.webp",
        ],
        "haremu_02": [
            "images/cg/hv/hv006a.webp",
            "images/cg/hv/hv006b.webp",
            "images/cg/hv/hv006c.webp",
            "images/cg/hv/hv006d.webp",
            "images/cg/hv/hv006e.webp",
            "images/cg/hv/hv006f.webp",
            "images/cg/hv/hv006h.webp",
            "images/cg/hv/hv006i.webp",
            "images/cg/hv/hv006j.webp",
        ],
        "others_01": [
            "images/bg/bg01DAY.webp",
            "images/bg/bg01EVE.webp",
            "images/bg/bg01LIG.webp",
            "images/bg/bg01NIG.webp",
        ],
        "others_02": [
            "images/bg/bg02DAY.webp",
            "images/bg/bg02LIG.webp",
            "images/bg/bg02LIG_sp.webp",
        ],
        "others_03": [
            "images/bg/bg03DAY.webp",
            "images/bg/bg03LIG.webp",
        ],
        "others_04": [
            "images/bg/bg04DAY.webp",
        ],
        "others_05": [
            "images/bg/bg11DAY.webp",
            "images/bg/bg11EVE.webp",
            "images/bg/bg11LIG.webp",
            "images/bg/bg11NIG.webp",
        ],
        "others_06": [
            "images/bg/bg12DAY.webp",
            "images/bg/bg12LIG.webp",
        ],
        "others_07": [
            "images/bg/bg13DAY.webp",
            "images/bg/bg13DAY_a.webp",
            "images/bg/bg13LIG.webp",
            "images/bg/bg13LIG_a.webp",
        ],
        "others_08": [
            "images/bg/bg14DAY.webp",
        ],
        "others_09": [
            "images/bg/bg21DAY.webp",
            "images/bg/bg21LIG.webp",
            "images/bg/bg21NIG.webp",
        ],
        "others_10": [
            "images/bg/bg22DAY.webp",
            "images/bg/bg22NIG.webp",
        ],
        "others_11": [
            "images/bg/bg23DAY.webp",
            "images/bg/bg23EVE.webp",
            "images/bg/bg23LIG.webp",
        ],
        "others_12": [
            "images/bg/bg24DAY.webp",
            "images/bg/bg24LIG.webp",
            "images/bg/bg24NIG.webp",
        ],
        "others_13": [
            "images/bg/bg25DAY.webp",
            "images/bg/bg25LIG.webp",
            "images/bg/bg25NIG.webp",
        ],
        "others_14": [
            "images/bg/bg26DAY.webp",
            "images/bg/bg26LIG.webp",
            "images/bg/bg26NIG.webp",
        ],
        "others_15": [
            "images/bg/bg31DAY.webp",
            "images/bg/bg31EVE.webp",
            "images/bg/bg31LIG.webp",
        ],
        "others_16": [
            "images/bg/bg32DAY.webp",
            "images/bg/bg32EVE.webp",
            "images/bg/bg32LIG.webp",
        ],
        "others_17": [
            "images/bg/bg33DAY.webp",
            "images/bg/bg33EVE.webp",
            "images/bg/bg33LIG.webp",
        ],
        "others_18": [
            "images/bg/bg34DAY.webp",
            "images/bg/bg34EVE.webp",
            "images/bg/bg34LIG.webp",
        ],
        "others_19": [
            "images/bg/bg35DAY.webp",
            "images/bg/bg35EVE.webp",
            "images/bg/bg35LIG.webp",
            "images/bg/bg35NIG.webp",
        ],
        "others_20": [
            "images/bg/bg36DAY.webp",
            "images/bg/bg36EVE.webp",
            "images/bg/bg36LIG.webp",
            "images/bg/bg36NIG.webp",
        ],
        "others_21": [
            "images/bg/bg37DAY.webp",
            "images/bg/bg37EVE.webp",
            "images/bg/bg37LIG.webp",
        ],
        "others_22": [
            "images/bg/bg41DAY.webp",
            "images/bg/bg41EVE.webp",
            "images/bg/bg41LIG.webp",
            "images/bg/bg41NIG.webp",
        ],  
        "others_23": [
            "images/bg/bg42DAY.webp",
            "images/bg/bg42EVE.webp",
            "images/bg/bg42LIG.webp",
            "images/bg/bg42NIG.webp",
        ],
    }